site_name: ziBot Documentation

theme: readthedocs

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - pymdownx.superfences
  - pymdownx.tabbed

nav:
  - Home: 
    - ziBot: index.md
  - Getting started: 
    - Setup: getting-started.md
    - Customization: customization.md
    - License: license.md
  - Commands: 
    - Command List: commands.md
